/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static io.restassured.RestAssured.when;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testelistaDadosDoUsuario() {
        when().
           get("https://reqres.in/api/users?page=2").
        then().
            statusCode(HttpStatus.SC_OK).
            body("page", is(2)).
            body("data", is(notNullValue()));
    }

    @Test
    public void testecriarUsuarioComSucesso() {
        given().
            contentType(ContentType.JSON).
            body("{\"name\": \"morpheus\", \"job\": \"leader\"}").
        when().
            post("https://reqres.in/api/users").
        then().
            statusCode(HttpStatus.SC_CREATED).
            body("name", is("morpheus"));

    }
}
